version: '3.7'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5453:5432'

  provider_a:
    build: provider_a
    volumes:
      - ./provider_a:/provider_a
    ports:
      - '8000:8000'
  
  provider_b:
    build: provider_b
    volumes:
      - ./provider_b:/provider_b
    ports:
      - '8001:8001'
  
  airflow: 
    build: airflow
    volumes:
      - ./airflow:/airflow
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_PORT: 5432
      POSTGRES_DB: "postgres"
    ports:
      - '9000:8002'
