"""init

Revision ID: 44a8806968a4
Revises: 
Create Date: 2022-02-08 19:38:31.290969

"""
import sqlalchemy_jsonfield
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a8806968a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airflowresults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('items', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airflowresults')
    # ### end Alembic commands ###
